# Official documentation at http://goreleaser.com
project_name: kk
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/kk/main.go
  binary: kk
  goarch:
    - amd64
    - arm64
  goos:
    - linux
    # only for test purpose currently
    - darwin
  ldflags:
    - -X github.com/kubesphere/kubekey/version.version={{.Version}}
    - -X github.com/kubesphere/kubekey/version.gitCommit={{.ShortCommit}}
    - -X github.com/kubesphere/kubekey/version.metadata=unreleased
dist: bin
archives:
- name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    linux: linux
    amd64: amd64
    arm64: arm64
  files:
    - README.md
    - README_zh-CN.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next-{{.ShortCommit}}"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  - file_name_template: "{{ .Binary }}-{{.Os}}-{{.Arch}}"
    homepage: https://github.com/kubesphere/kubekey
    description: "The Next-gen Installer: Installing Kubernetes and KubeSphere v3.0.0 fastly, flexibly and easily"
    maintainer: kubesphere authors
    license: Apache-2.0
    vendor: Kubesphere
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    replacements:
      amd64: 64bit
      arm64: arm64
      linux: linux
