apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubekey
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubekey
  template:
    metadata:
      labels:
        name: kubekey
    spec:
      serviceAccountName: kubekey
      containers:
        - name: kubekey
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - kubekey
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubekey"
